# Imports

In [1]:
import pandas as pd
import numpy as np

In [17]:
pd.set_option('display.max_columns', None) # Make sure that we can see all of the columns

# Getting Data

## Data Attributes

- Year – Year of the flight.

- Month – Month of the flight.

- DayofMonth – Day of the month the flight departed.

- DayOfWeek – Day of the week (1 = Monday, 7 = Sunday).

- DOT_ID_Marketing_Airline – Code identifying unique airline carrier.

- OriginAirportID – Origin airport code.

- OriginAirportSeqID - Origin airport to identify a unique airport at a given point in time.

- OriginCityName - Origin airport, city name

- DestAirportID – Destination airport code (IATA).

- DestAirportSeqID - Destination airport to identify a unique airport at a given point in time.

- DestCityName - Destination airport, city name.

- CRSDepTime – Scheduled departure time (local).

- DepTime – Actual departure time (local).

- DepDelayMinutes – Departure delay in minutes; early departures set to 0.

- DepDel15 - Departure delay indicator, 15 mins or more.

- DepartureDelayGroups - Departure delay intervals from <-15 to >180, every 15 minutes.

- ArrTime – Actual arrival time (local).

- ArrDelayMinutes – Arrival delay in minutes; early arrivals set to 0.

- ArrDel15 - Arrival delay indicator, 15 mins or more.

- ArrivalDelayGroups - Arrival delay intervals from <-15 to >180, every 15 minutes.

- Cancelled – Flight cancelled flag (1 = Yes).

- CancellationCode - Specifies the reason for cancellation

- CRSElapsedTime – Scheduled flight duration in minutes.

- ActualElapsedTime – Actual flight duration in minutes.

- AirTime – Actual in-air time in minutes.

- Distance – Distance between origin and destination (miles).

- CarrierDelay – Minutes of delay due to airline-controlled issues.

- WeatherDelay – Minutes of delay due to weather.

- NASDelay – Minutes of delay due to the National Airspace System (ATC).

- SecurityDelay – Minutes of delay due to security-related reasons.

- LateAircraftDelay – Minutes of delay caused by the late arrival of the same aircraft from a previous flight.

In [18]:
df = pd.read_csv("2024_FULL_YEAR.csv")
df.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,MKT_CARRIER_AIRLINE_ID,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_NAME,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_NAME,CRS_DEP_TIME,DEP_TIME,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,ARR_TIME,ARR_DELAY_NEW,ARR_DEL15,ARR_DELAY_GROUP,CANCELLED,CANCELLATION_CODE,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2024,1,1,1,1,19393,10140,1014005,"Albuquerque, NM",10423,1042302,"Austin, TX",700,707.0,7.0,0.0,0.0,950.0,15.0,1.0,1.0,0.0,NaN,95.0,103.0,619.0,7.0,0.0,8.0,0.0,0.0
1,2024,1,1,1,1,19393,10140,1014005,"Albuquerque, NM",10423,1042302,"Austin, TX",1830,1826.0,0.0,0.0,-1.0,2112.0,2.0,0.0,0.0,0.0,NaN,100.0,106.0,619.0,NaN,NaN,NaN,NaN,NaN
2,2024,1,1,1,1,19393,10140,1014005,"Albuquerque, NM",10800,1080003,"Burbank, CA",1420,1426.0,6.0,0.0,0.0,1516.0,0.0,0.0,-1.0,0.0,NaN,130.0,110.0,672.0,NaN,NaN,NaN,NaN,NaN
3,2024,1,1,1,1,19393,10140,1014005,"Albuquerque, NM",10821,1082106,"Baltimore, MD",1500,1514.0,14.0,0.0,0.0,2050.0,15.0,1.0,1.0,0.0,NaN,215.0,216.0,1670.0,14.0,0.0,1.0,0.0,0.0
4,2024,1,1,1,1,19393,10140,1014005,"Albuquerque, NM",11259,1125904,"Dallas, TX",530,527.0,0.0,0.0,-1.0,805.0,0.0,0.0,-1.0,0.0,NaN,105.0,98.0,580.0,NaN,NaN,NaN,NaN,NaN

In [19]:
print(df.shape)

(7546988, 31)

# Null handling

First let's check how many null values there are in the dataframe

In [6]:
df.isnull().sum()

YEAR                            0
QUARTER                         0
MONTH                           0
DAY_OF_MONTH                    0
DAY_OF_WEEK                     0
MKT_CARRIER_AIRLINE_ID          0
ORIGIN_AIRPORT_ID               0
ORIGIN_AIRPORT_SEQ_ID           0
ORIGIN_CITY_NAME                0
DEST_AIRPORT_ID                 0
DEST_AIRPORT_SEQ_ID             0
DEST_CITY_NAME                  0
CRS_DEP_TIME                    0
DEP_TIME                    98935
DEP_DELAY_NEW               99245
DEP_DEL15                   99245
DEP_DELAY_GROUP             99245
ARR_TIME                   104527
ARR_DELAY_NEW              121739
ARR_DEL15                  121739
ARR_DELAY_GROUP            121739
CANCELLED                       0
CANCELLATION_CODE         7444080
CRS_ELAPSED_TIME                1
ACTUAL_ELAPSED_TIME        121739
DISTANCE                        0
CARRIER_DELAY             6015904
WEATHER_DELAY             6015904
NAS_DELAY                 6015904
SECURITY_DELAY            6015904
LATE_AIRCRAFT_DELAY       6015904
dtype: int64

## Investing missing values independent of delays and cancellations
- Investigating why there might be one one missing value for the "CRS_elaspsed_time"

In [23]:
df[df['CRS_ELAPSED_TIME'].isnull()]

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,MKT_CARRIER_AIRLINE_ID,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_NAME,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_NAME,CRS_DEP_TIME,DEP_TIME,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,ARR_TIME,ARR_DELAY_NEW,ARR_DEL15,ARR_DELAY_GROUP,CANCELLED,CANCELLATION_CODE,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
786789,2024,1,2,11,7,20416,10821,1082106,"Baltimore, MD",14843,1484306,"San Juan, PR",1800,1804.0,4.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,A,NaN,NaN,1565.0,NaN,NaN,NaN,NaN,NaN

We see that this flight was scheduled from Baltimore, MD to San Juan, PR. So, we can impute this value by taking the median CRS_elapsed_time of all other flights that flew this route. Since scheduled flight times primarily depend on the route (i.e., origin–destination pair) and are relatively stable across flights of the same route, imputing the missing value using data from other flights between these two cities is a reasonable and data-consistent approach.

In [29]:
route_df = df[
    (df["ORIGIN_CITY_NAME"] == "Baltimore, MD") &
    (df["DEST_CITY_NAME"] == "San Juan, PR")
]

mean_elapsed = route_df["CRS_ELAPSED_TIME"].median(skipna=True)
print(mean_elapsed)

mask = (
    (df["ORIGIN_CITY_NAME"] == "Baltimore, MD") &
    (df["DEST_CITY_NAME"] == "San Juan, PR") &
    (df["CRS_ELAPSED_TIME"].isna())
)
df.loc[mask, "CRS_ELAPSED_TIME"] = mean_elapsed

df[df['CRS_ELAPSED_TIME'].isnull()]

240.0

Empty DataFrame
Columns: [YEAR, QUARTER, MONTH, DAY_OF_MONTH, DAY_OF_WEEK, MKT_CARRIER_AIRLINE_ID, ORIGIN_AIRPORT_ID, ORIGIN_AIRPORT_SEQ_ID, ORIGIN_CITY_NAME, DEST_AIRPORT_ID, DEST_AIRPORT_SEQ_ID, DEST_CITY_NAME, CRS_DEP_TIME, DEP_TIME, DEP_DELAY_NEW, DEP_DEL15, DEP_DELAY_GROUP, ARR_TIME, ARR_DELAY_NEW, ARR_DEL15, ARR_DELAY_GROUP, CANCELLED, CANCELLATION_CODE, CRS_ELAPSED_TIME, ACTUAL_ELAPSED_TIME, DISTANCE, CARRIER_DELAY, WEATHER_DELAY, NAS_DELAY, SECURITY_DELAY, LATE_AIRCRAFT_DELAY]
Index: []

## Investigating columns with many missing values 
It makes sense that we would have a lot of missing values since many attributes are only relevant for delayed flights or cancelled flights (e.g. we see so many null values for the "Cancellation_code" feature because most of the flights are not cancelled, and hence, have null values for this feature if the flight is not cancelled). This means that these null values are **not random**. 

To account for that, we can separate our data based on the flight outcome.

### Separating completed vs. cancelled flights
We can separate our dataframe based on completed flights and cancelled flights because cancelled flights generally have meaningless delay data (even if they were initially delayed before cancelling). We will create new dataframes that categorize the flights based on completed vs. cancelled, but we will impute the values on the original dataframe

In [36]:
df_cancelled = df[df['CANCELLED'] == 1]
print(f"Shape of cancelled flights dataframe: {df_cancelled.shape}")

df_completed = df[df['CANCELLED'] == 0]
print(f"Shape of completed flights dataframe: {df_completed.shape}")

Shape of cancelled flights dataframe: (102908, 31)
Shape of completed flights dataframe: (7444080, 31)

All cancelled flights are missing information about arrivals, which makes sense since the flights were not carried through. Some cancelled flights have departure delay information which suggests that some flights were cancelled much closer to the intended scheduled time of takeoff.

In [33]:
df_cancelled.isnull().sum()

YEAR                           0
QUARTER                        0
MONTH                          0
DAY_OF_MONTH                   0
DAY_OF_WEEK                    0
MKT_CARRIER_AIRLINE_ID         0
ORIGIN_AIRPORT_ID              0
ORIGIN_AIRPORT_SEQ_ID          0
ORIGIN_CITY_NAME               0
DEST_AIRPORT_ID                0
DEST_AIRPORT_SEQ_ID            0
DEST_CITY_NAME                 0
CRS_DEP_TIME                   0
DEP_TIME                   98935
DEP_DELAY_NEW              99245
DEP_DEL15                  99245
DEP_DELAY_GROUP            99245
ARR_TIME                  102908
ARR_DELAY_NEW             102908
ARR_DEL15                 102908
ARR_DELAY_GROUP           102908
CANCELLED                      0
CANCELLATION_CODE              0
CRS_ELAPSED_TIME               0
ACTUAL_ELAPSED_TIME       102908
DISTANCE                       0
CARRIER_DELAY             102908
WEATHER_DELAY             102908
NAS_DELAY                 102908
SECURITY_DELAY            102908
LATE_AIRCRAFT_DELAY       102908
dtype: int64

### Delays in the completed flights
- All flights should have ARR_TIME if they were completed 
- Are the columns that are missing "18831" values all the same rows?

In [37]:
df_completed.isnull().sum()

YEAR                            0
QUARTER                         0
MONTH                           0
DAY_OF_MONTH                    0
DAY_OF_WEEK                     0
MKT_CARRIER_AIRLINE_ID          0
ORIGIN_AIRPORT_ID               0
ORIGIN_AIRPORT_SEQ_ID           0
ORIGIN_CITY_NAME                0
DEST_AIRPORT_ID                 0
DEST_AIRPORT_SEQ_ID             0
DEST_CITY_NAME                  0
CRS_DEP_TIME                    0
DEP_TIME                        0
DEP_DELAY_NEW                   0
DEP_DEL15                       0
DEP_DELAY_GROUP                 0
ARR_TIME                     1619
ARR_DELAY_NEW               18831
ARR_DEL15                   18831
ARR_DELAY_GROUP             18831
CANCELLED                       0
CANCELLATION_CODE         7444080
CRS_ELAPSED_TIME                0
ACTUAL_ELAPSED_TIME         18831
DISTANCE                        0
CARRIER_DELAY             5912996
WEATHER_DELAY             5912996
NAS_DELAY                 5912996
SECURITY_DELAY            5912996
LATE_AIRCRAFT_DELAY       5912996
dtype: int64

In [ ]:
df_completed[(df_completed['ARR_DELAY_NEW'].isnull()) & 
             (df_completed['ARR_DEL15'].isnull()) & 
             (df_completed['ARR_DELAY_GROUP'].isnull()) & 
             (df_completed['ACTUAL_ELAPSED_TIME'].isnull())].shape

# This means that there are 18831 flights that are all missing information on the arrival time

(18831, 31)

We will impute all of the 18831 rows that are missing arrival information by using the CRS_ELAPSED_TIME which is the scheduled flight duration, combined with the DEP_DELAY_NEW which the departure delayed minutes. For these cases, imputing ACTUAL_ELAPSED_TIME as the sum of the scheduled elapsed time (CRS_ELAPSED_TIME) and departure delay (DEP_DELAY_NEW) is reasonable since actual flight duration typically equals the planned duration plus the initial delay. Similarly, for missing arrival delay fields, imputing with the departure delay maintains consistency across delay-related variables.

In [48]:
# Impute ACTUAL_ELAPSED_TIME
df_completed["ACTUAL_ELAPSED_TIME"] = df_completed["ACTUAL_ELAPSED_TIME"].fillna(
    df_completed["CRS_ELAPSED_TIME"] + df_completed["DEP_DELAY_NEW"]
)

# Impute ARR_DELAY_NEW (minutes delayed from arrival)
df_completed["ARR_DELAY_NEW"] = df_completed["ARR_DELAY_NEW"].fillna(df_completed["DEP_DELAY_NEW"])

# Impute ARR_DEL15 (arrival delayed 15 mins or not)
df_completed.loc[df_completed["ARR_DEL15"].isna(), "ARR_DEL15"] = np.where(
    df_completed.loc[df_completed["ARR_DEL15"].isna(), "ARR_DELAY_NEW"] >= 15, 1, 0
)

# Impute ARR_DELAY_GROUP
mask = df_completed["ARR_DELAY_GROUP"].isna()

bins = np.floor(df_completed.loc[mask, "ARR_DELAY_NEW"] / 15)
bins = np.clip(bins, -2, 12).astype("Int64") 

df_completed.loc[mask, "ARR_DELAY_GROUP"] = bins

/var/folders/h1/w_jtl0654ns96y8ngd075fj40000gn/T/ipykernel_27826/2655069473.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_completed["ACTUAL_ELAPSED_TIME"] = df_completed["ACTUAL_ELAPSED_TIME"].fillna(
/var/folders/h1/w_jtl0654ns96y8ngd075fj40000gn/T/ipykernel_27826/2655069473.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_completed["ARR_DELAY_NEW"] = df_completed["ARR_DELAY_NEW"].fillna(df_completed["DEP_DELAY_NEW"])

In [49]:
df_completed.isnull().sum()

YEAR                            0
QUARTER                         0
MONTH                           0
DAY_OF_MONTH                    0
DAY_OF_WEEK                     0
MKT_CARRIER_AIRLINE_ID          0
ORIGIN_AIRPORT_ID               0
ORIGIN_AIRPORT_SEQ_ID           0
ORIGIN_CITY_NAME                0
DEST_AIRPORT_ID                 0
DEST_AIRPORT_SEQ_ID             0
DEST_CITY_NAME                  0
CRS_DEP_TIME                    0
DEP_TIME                        0
DEP_DELAY_NEW                   0
DEP_DEL15                       0
DEP_DELAY_GROUP                 0
ARR_TIME                     1619
ARR_DELAY_NEW                   0
ARR_DEL15                       0
ARR_DELAY_GROUP                 0
CANCELLED                       0
CANCELLATION_CODE         7444080
CRS_ELAPSED_TIME                0
ACTUAL_ELAPSED_TIME             0
DISTANCE                        0
CARRIER_DELAY             5912996
WEATHER_DELAY             5912996
NAS_DELAY                 5912996
SECURITY_DELAY            5912996
LATE_AIRCRAFT_DELAY       5912996
dtype: int64

### Merge the imputed completed flight values back to the original df

In [51]:
df_completed = df_completed.copy()
df_completed["index"] = df_completed.index
df["index"] = df.index

cols_to_update = [
    "ACTUAL_ELAPSED_TIME", "ARR_DELAY_NEW", "ARR_DEL15", "ARR_DELAY_GROUP"
]

df.update(df_completed[cols_to_update])

# Impute delay reasons' values as 0 for delayed flights

In [61]:
delay_cols = [
    "CARRIER_DELAY",
    "WEATHER_DELAY",
    "NAS_DELAY",
    "SECURITY_DELAY",
    "LATE_AIRCRAFT_DELAY"
]

mask_delayed = (df["DEP_DEL15"] == 1) & (df["CANCELLED"] == 0)

df.loc[mask_delayed, delay_cols] = df.loc[mask_delayed, delay_cols].fillna(0)

df.isnull().sum()

YEAR                            0
QUARTER                         0
MONTH                           0
DAY_OF_MONTH                    0
DAY_OF_WEEK                     0
MKT_CARRIER_AIRLINE_ID          0
ORIGIN_AIRPORT_ID               0
ORIGIN_AIRPORT_SEQ_ID           0
ORIGIN_CITY_NAME                0
DEST_AIRPORT_ID                 0
DEST_AIRPORT_SEQ_ID             0
DEST_CITY_NAME                  0
CRS_DEP_TIME                    0
DEP_TIME                    98935
DEP_DELAY_NEW               99245
DEP_DEL15                   99245
DEP_DELAY_GROUP             99245
ARR_TIME                   104527
ARR_DELAY_NEW              102908
ARR_DEL15                  102908
ARR_DELAY_GROUP            102908
CANCELLED                       0
CANCELLATION_CODE         7444080
CRS_ELAPSED_TIME                0
ACTUAL_ELAPSED_TIME        102908
DISTANCE                        0
CARRIER_DELAY                   0
WEATHER_DELAY                   0
NAS_DELAY                       0
SECURITY_DELAY                  0
LATE_AIRCRAFT_DELAY             0
index                           0
dtype: int64

# Create new csv

## Now we are finally done with null handling
- All non cancelled flights have null values for the "CANCELLATION_CODE" 
- Some cancelled flights have have departure information, hence why there are more null values for arrival information than departure information
- Some columns are missing the "ARR_TIME"

## What was done
- Imputed the one null "CRS_ELAPSED_TIME" value using median value for all flights that flew from Baltimore to San Juan
- Imputed "ACTUAL_ELAPSED_TIME", "ARR_DELAY_NEW", "ARR_DEL15", "ARR_DELAY_GROUP" for all completed flights using "CRS_ELAPSED_TIME" combined with "DEP_DELAY_NEW"
- Imputed the delayed reasons "CARRIER_DELAY", "WEATHER_DELAY", "NAS_DELAY", "SECURITY_DELAY", "LATE_AIRCRAFT_DELAY" for delayed flights by replacing null values with 0 (0 minutes delay due to the given reason)

In [63]:
df.to_csv("FLIGHTS.csv", index=False)